### ISSUE TITLE
Collapse All buttom in explorer panel

### ISSUE THREAD

**Issue by georgepaoli** [fernandoescolar/vscode-solution-explorer#1]
Please, include collapse all buttom in explorer panel.

Thanks.

**Comment by fernandoescolar** [comment]
We'll have to wait to the solution of this issue: [Microsoft/vscode#43879](https://github.com/Microsoft/vscode/issues/43879)

**Comment by fernandoescolar** [comment]
https://github.com/Microsoft/vscode/issues/30918

**Comment by ckarcz** [comment]
the vscode bug is marked as fixed. can we please have it added as a feature? ❤️

a sync to open file button like visual studio has would also be a great addition.
