### ISSUE TITLE
vscode-solution-explorer not show in sidebar explorer after install

### ISSUE THREAD

**Issue by pabloandrei** [fernandoescolar/vscode-solution-explorer#101]
Hello.
After installed, the vscode-solution-explorer not show in sidebar explorer.

Anybody could help me?

Sidebar explorer:
![image](https://user-images.githubusercontent.com/16004192/65905806-a76cc100-e397-11e9-99a2-21db3f5af5d8.png)

My extensions:
![image](https://user-images.githubusercontent.com/16004192/65906068-2c57da80-e398-11e9-8e08-853934df5975.png)

Im using Ubuntu 18.04.3 LTS and Vistual Studio Code.

Sincerely,
Pablo

**Comment by fernandoescolar** [comment]
Hello,

Have you opened a folder? And could you send the extension settings you have configured?

Thanks

**Comment by pabloandrei** [comment]
Hello, 
Im trying open this project (https://github.com/dotnet-architecture/eShopOnContainers). (local cloned)

Which "extension settings you have configured"?

TKS

**Comment by pabloandrei** [comment]
This setting file?
$HOME/.config/Code/User/settings.json

**Comment by pabloandrei** [comment]
Now the extension show.. after boot.
Tks
