### ISSUE TITLE
I can't open downloaded solution with vscode

### ISSUE THREAD

**Issue by CHANGXU6** [fernandoescolar/vscode-solution-explorer#103]
I use visual studio in windows system and I can open file(.sln) with visual studio 2019. however when I move to macOS, I can't open .sln file with vs code.

I can't figure out what is the issue. can you help. thanks.
<img width="1396" alt="屏幕快照 2019-10-16 下午10 22 31" src="https://user-images.githubusercontent.com/26312588/66928196-998b9100-f063-11e9-99b2-e1f84e230ddc.png">
<img width="1396" alt="屏幕快照 2019-10-16 下午10 24 17" src="https://user-images.githubusercontent.com/26312588/66928284-ba53e680-f063-11e9-8aa8-cc03a05e063d.png">

**Comment by fernandoescolar** [comment]
Hi, 

Could you try opening "Program Files\Mediadata Solutions\CustomFunction Development Utility" folder in vscode and check if it works?
Could you provide your ".csproj" file or someone like it?
Could you capture the vscode-solution-explorer output window? 

Thanks in advance!
