### ISSUE TITLE
Solution not found if its project is opened in MSVS 2019

### ISSUE THREAD

**Issue by roman-orekhov** [fernandoescolar/vscode-solution-explorer#107]
Consider this workflow: open MSVS 2019, open `path/to/project.vcxproj`, folder `path/to` also contains `project.sln`. Now open VS Code, open folder `path/to`, click on Solution.
I see no solution there, it's not found. Repeated refreshing doesn't help.

If I open the same folder in VS Code while MSVS isn't running, everything is Ok, even if I run MSVS afterwards.

**Comment by fernandoescolar** [comment]
Possibly MSVS has a file lock in windows. This type of problem cannot be solved on that operating system.
