### ISSUE TITLE
Solution Opened with a Weird Bug

### ISSUE THREAD

**Issue by AbbyDeng** [fernandoescolar/vscode-solution-explorer#109]
hello, all the screenshots here might not be full info as I'm investigating in using Visual Studio Code for solutions in my company.
I have a folder dev with a .sln file under it, so this weird bug appeared after I opened this dev folder:
![image](https://user-images.githubusercontent.com/8296117/69269543-1c819900-0b86-11ea-945d-231b64110ef6.png)

but it should be like this (in Visual Studio 2017):
![image](https://user-images.githubusercontent.com/8296117/69269568-2c00e200-0b86-11ea-860d-917e2e726776.png)

**Comment by MaoKwen** [comment]
Same problem here.
The error occurred in the generated .sln file from [JoeyDeVries/LearnOpenGL](https://github.com/JoeyDeVries/LearnOpenGL) with cmake version 3.17.2

**Comment by fernandoescolar** [comment]
Would you mind sending me a .csproj file with this error?
