### ISSUE TITLE
Add ability to Include/Exclude Items

### ISSUE THREAD

**Issue by fitdev** [fernandoescolar/vscode-solution-explorer#11]
It would be awesome if there was ability to:

- Exclude selected items
- Include selected items
- Specify type of "include" action on the items to be included (i.e. Compile by default for *.cs for example) via prompt
- Ability to show (see) excluded files and folders (so they can be right-clicked, and included)

**Comment by olemarius** [comment]
+1

**Comment by dzmitry-lahoda** [comment]
I have `MyProject.csproj` with excludes produced by Unity3D IDE. I hope do not see these files if `Solution Explorer` if these are defined as:

```
  <ItemGroup>
    <None Remove=".gitignore" />
    <None Remove="MyProject.asmdef" />
    <None Remove="MyProject.csproj.DotSettings" />
    <None Remove="**/*.meta" />
  </ItemGroup>
```
