### ISSUE TITLE
VSCode-solution-explorer not show in sidebar explorer after install - [Ubuntu 16.04 LTS] [VsCode 1.41.0]

### ISSUE THREAD

**Issue by joaopauloit** [fernandoescolar/vscode-solution-explorer#114]
Hello.
Anybody could help me?

After installed, the vscode-solution-explorer not show in sidebar explorer.
Sidebar explorer:

![image](https://user-images.githubusercontent.com/502322/71045512-f105b600-2113-11ea-9bc2-c3b8ea65ca27.png)

Extension enabled:
![image](https://user-images.githubusercontent.com/502322/71045577-2e6a4380-2114-11ea-986b-5c0cf570475e.png)

I already openned folder that contains a .sln, but don't work.
I too checked my settings.json in located ".config/code/User", your content is empty. So, it should show my solution explorer,  because to default it is "true" to visible. Am I right?

Fernando, congrats to created extension.

Thank you guys

**Comment by fernandoescolar** [comment]
Hi,

As I can see in your snapshots, the extension icon is the last one in the left bar (the visual studio one). Related with this issue, I think we should update the documentation of the extension...

Thanks!
