### ISSUE TITLE
No SOLUTION EXPLORER menu

### ISSUE THREAD

**Issue by joved-git** [fernandoescolar/vscode-solution-explorer#115]
Hi Fernando,

I just add today your extension but I cannot see the SOLUTION_EXPLORER menu in the left.

My OS is Win 10 Pro.
The version of my VSCode is: 1.41.1.
The Extension version is: 0.3.7.

Could you help me, please ? Maybe, I forgot to do something simple (config...).

Thanks for your help.
Joël.

**Comment by mough** [comment]
I'm having the same issue
macOS Sierra 10.12.6
VSCode: 1.41.1
Extension version: 0.3.7.

**Comment by RikWaspcroft** [comment]
Me too
Win 10 Pro (OS Build 19.041.1)
VSCode: 1.41.1
Extension version: 0.3.7.

**Comment by fernandoescolar** [comment]
Things to check:
- Have you opened a folder in vscode? This is mandatory to start this extension.
- In the vscode-solution-explorer settings wich value have you selected in "Vssolution: Show Mode"?
![image](https://user-images.githubusercontent.com/3491424/72251923-cf0e2f00-35fe-11ea-9f28-e330d30b0b3a.png)

If you selected:
- "activityBar": It will be shown in the left icons bar.
- "explorer": It will be shown in the explorer activity bar as a workspace. In this case be sure you have not hide this section.
- "none": It wont be shown
