### ISSUE TITLE
How to Add a C++Project(.vcxproj) directly in vscode-solution-explorer

### ISSUE THREAD

**Issue by houwayhsu** [fernandoescolar/vscode-solution-explorer#116]
I want to add a C++Project(.vcxproj) directly in vscode-solution-explorer

After installing the extension, I tried to add a new solution [right click >> Create new empty solution], the Terminal shows:
“'dotnet' is not recognized as an internal or external command operable program or batch file”

Therefore, I downloaded “.Net Core SDK” and set the path “C:\Program Files (x86)\dotnet” to the environment variable in order to use “dotnet” command. And it worked. I successfully created a “.sln”.
 ![dotnet](https://user-images.githubusercontent.com/59817015/72235449-329f5900-360d-11ea-90fc-ab9c86fc716b.png)

However, when I try to create a C++ project(.vcxproj), [right click >> add project >> Console Application], I found no option to choose. There are only “C#, F#, VB“.
![SelectLanguage](https://user-images.githubusercontent.com/59817015/72235438-23201000-360d-11ea-8777-cf8a67d1fc4e.png)

After trying to find answers on Google, I realized that “.Net Core” doesn’t support C++ originally. And the reason why Visual Studio can create C++ project is that I added a workload, called “Desktop Development with C++”. But I didn’t find any method to install “Desktop Development with C++” individually.
![DesktopDevelopmentWithC++](https://user-images.githubusercontent.com/59817015/72235391-e3592880-360c-11ea-9a09-c273f98e27bc.png)

So, What should I do?
Here are some possible methods I could imagine:
(1)	Download the “Desktop Development with C++” individually.
(2)	Set “Net Desktop Development” and “Desktop Development with C++” of VS to the environment variable.

It looks like Method(1) may not work.
And I don’t know whether Method(2) will work and which path should I set.
Or, there are some Method(3) to choose...

**Comment by fernandoescolar** [comment]
`vscode-solution-explorer` only supports .net core projects. It was a technical decission due to vscode is multiplatform and it should work  in Windows and also in macos and linux/unix.

Thanks to @mwpenny in the PR #58, it also supports the read of an existing C/C++ projects (.vcxproj).

So, answering your question about what should you do, I think you could create this feature and send a PR. If it works I will be happy to merge it and create a new version :).

**Comment by houwayhsu** [comment]
> `vscode-solution-explorer` only supports .net core projects. It was a technical decission due to vscode is multiplatform and it should work in Windows and also in macos and linux/unix.
> 
> Thanks to @mwpenny in the PR #58, it also supports the read of an existing C/C++ projects (.vcxproj).
> 
> So, answering your question about what should you do, I think you could create this feature and send a PR. If it works I will be happy to merge it and create a new version :).

I got it!! Thanks for your response. Hope someday it will work.
