### ISSUE TITLE
Consider adding to the C# extension project?

### ISSUE THREAD

**Issue by ryzngard** [fernandoescolar/vscode-solution-explorer#119]
The official csharp extension is at https://github.com/OmniSharp/omnisharp-vscode 

Have you considered contributing some of this work there?

**Comment by fernandoescolar** [comment]
I think Microsoft people are not interested in a solution explorer feature. And I would not like to mess up this great extension with my stuff... so the answer is: no, I haven't.

Thanks!

**Comment by ryzngard** [comment]
I'm Microsoft people, and I'm interested :)

**Comment by fernandoescolar** [comment]
I have taken a look at omnisharp-vscode source code, it seems everything is based on a omnisharp-roslyn, so I guess if I would like to contribute to this project I should create the server side code in c# (omnisharp-roslyn) and the client code in typescript (omnisharp-vscode), isn't it?
