### ISSUE TITLE
[BUG] Solution Explorer window is cut off after resizing Explorer window

### ISSUE THREAD

**Issue by Tymski** [fernandoescolar/vscode-solution-explorer#121]
It appears that Solution Explorer window size is set to Explorer window size. It doesn't happen until you open Explorer window. If it is closed, everything works as expected
![explorer](https://user-images.githubusercontent.com/8183632/74152348-68386180-4c0e-11ea-9aec-59f5fc8627ba.gif)

**Comment by fernandoescolar** [comment]
I think this is a bug in vscode. I can not do anything related with the treeview renderer...
