### ISSUE TITLE
Solution explorer is shown in explorer window although preference is set to acitivityBar

### ISSUE THREAD

**Issue by neeohw** [fernandoescolar/vscode-solution-explorer#122]
Since a few days solution explorer is suddenly showing in the explorer window although I didn't change the setting.
![image](https://user-images.githubusercontent.com/557168/74421725-c7d08000-4e4d-11ea-80b9-cf5cfbf62f94.png)

**Comment by karistonavila** [comment]
Same problem here. Started to happen after updating vscode to version 1.42.
