### ISSUE TITLE
it wasn`t shown on activityBar after update.I try to reboot my computer ,but it  still doesn`t work.

### ISSUE THREAD

**Issue by TreeMoons** [fernandoescolar/vscode-solution-explorer#124]
vscode version:
![image](https://user-images.githubusercontent.com/46921153/74581987-0d797e00-4ff1-11ea-8550-94ac37c7a14f.png)
settings:
![image](https://user-images.githubusercontent.com/46921153/74582089-0a32c200-4ff2-11ea-8d6a-44464316e2ea.png)

**Comment by fernandoescolar** [comment]
duplicate #122
