### ISSUE TITLE
csproj files with "Compile Include" don't show source files.

### ISSUE THREAD

**Issue by mdsitton** [fernandoescolar/vscode-solution-explorer#129]
I have a project that uses <Compile Include="" /> to specify the source files for the project. These projects do not show any files under the solution explorer.

Here is one of my project files:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Assets\Scripts\StrikeCore\**\*.cs" />
  </ItemGroup>

</Project>
```
Here is a screenshot inside vs code:

![image](https://user-images.githubusercontent.com/212897/76932249-771ecd80-68b8-11ea-9042-6c1f3a3e0ae9.png)

Here is a screenshot inside visual studio:
![image](https://user-images.githubusercontent.com/212897/76932276-8736ad00-68b8-11ea-9d64-25776047cbff.png)

The purpose of this project structure is sharing code between a .net core server application, and a Unity3d Project.

**Comment by mdsitton** [comment]
@fernandoescolar Any thoughts on this bug?

**Comment by ChaosZh** [comment]
Encounter same problem today.

**Comment by SneWs** [comment]
This would be a nice addition to have for sure.

And the Compile Include directive is a bit more complex as well as you can re-order Includes into groups using the Link attribute as well. 

For example:
`<Compile Include="../../Shared/Code/Server/*.cs" Link="Shared/Server/%(Filename)%(Extension)" />`

Will take all the CS files for the Server folder and place them in `Shared/Server/FilenameFromSource.cs` so not only would it need to be able to map the Include, it would also need to handle the Link attribute and expansion of pre-defined variable names such as %(Filename) 

Regards, and thank you for your effort and work on this extension, well done!
