### ISSUE TITLE
space in file path

### ISSUE THREAD

**Issue by BIKA-C** [fernandoescolar/vscode-solution-explorer#130]
Having trouble when there is a space in the path

Use quotations to wrap the path 
cd "C:\Program Files"

**Comment by alishchytovych** [comment]
Hello,
The same issue here. 
@fernandoescolar please update CliCommandBase: getWorkingFolder: just add quotes for the path.

**Comment by hilari0n** [comment]
I'd say this is a bug, not an enhancement. The extension executes an incorrect command for when there are spaces (or other special characters) in the path, i.e. it executes "cd" with an unquoted path, which is an incorrect behavior.
