### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [fernandoescolar/vscode-solution-explorer#132]
The [Open VSX Registry](https://open-vsx.org/?search=sln) does not include any extensions to handle solution files yet. It is the default extension provider of free "vscode" builds and it would be good to find this extension there, too.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by pm4rcin** [comment]
Hi, any progress on that? Are you planning to release it so people who use e.g. VSCodium could easily find and install it?

**Comment by fernandoescolar** [comment]
I have a problem:

![Screenshot 2022-09-05 at 11 43 10](https://user-images.githubusercontent.com/3491424/188419804-f20f5744-96f7-4416-b810-345bc0296ebe.png)

**Comment by fernandoescolar** [comment]
v0.7.2 has been already published automatically in Open VSX Registry

**Comment by pm4rcin** [comment]
Appreciate your effort even though it took a long time :D
