### ISSUE TITLE
feature request: Add Class and Add Interface from solution explorer.

### ISSUE THREAD

**Issue by tcfialho** [fernandoescolar/vscode-solution-explorer#133]
I want Add Class and Add Interface from solution explorer feature with default scaffold.

**Comment by m4ss1m0g** [comment]
I have written an extension [DotNet Core Add](https://marketplace.visualstudio.com/items?itemName=Solidcube.dotnet-core-add)  for adding Classes, Interfaces and CustomTemplates.
Maybe can be integrated.

**Comment by fernandoescolar** [comment]
It has been already implemented :)
