### ISSUE TITLE
Track active item only when Solution View is selected in side bar

### ISSUE THREAD

**Issue by svdHero** [fernandoescolar/vscode-solution-explorer#135]
**Is your feature request related to a problem? Please describe.**
I have the settings "vssolution.trackActiveItem" enabled, which is a great feature. However, when I am in the Source Control View something weird happens. Whenever I select a file to see the git diff, the side bar changes immediately to the Solution View and reveals the active item. That is so annoying!

**Describe the solution you'd like**
Do not change the Side bar view. Only reveal the active item when the Solution View is the active view in the side bar.

**Comment by jbactad** [comment]
hi @svdHero , I created a PR to fix this and along with the fix to not focus on the tree when revealing current file.

**Comment by svdHero** [comment]
@jbactad Thanks a lot for this contribution. Looks great. I hope this will make it into master and the VS Code Marketplace.
Is there any way, I can test this already?

**Comment by jbactad** [comment]
@svdHero , yes you can test it by compiling it using [vsce](https://www.npmjs.com/package/vsce) and installing it using `code` command.

**Comment by fernandoescolar** [comment]
#141 merged
