### ISSUE TITLE
Adding support for --disable-parallel and other flags to dotnet

### ISSUE THREAD

**Issue by IngvarKofoed** [fernandoescolar/vscode-solution-explorer#137]
I work with a solution where the `--disable-parallel` is needed for all dotnet commands.

It would therefor be really nice if I could add custom args to the dotnet command.

**Comment by fernandoescolar** [comment]
Now you can add your custom flags in the commands configuration: https://github.com/fernandoescolar/vscode-solution-explorer#run-dotnet-commands-in-solutions-and-projects
