### ISSUE TITLE
Issue with creating a new folder through solution explorer

### ISSUE THREAD

**Issue by ghost** [fernandoescolar/vscode-solution-explorer#143]
**Describe the bug**
Upon creating a new folder, the last created folder disappears.

**To Reproduce**
1. Go in Solution view
2. Create a folder
3. Create 2 folders in the folder you just created. One should disappear.

**Expected behavior**
Creating a new folder shouldn't make the other disappear.

**Screenshots**
<img src="https://i.imgur.com/dxweZZK.png">

**Environment (please complete the following information):**
 - OS: Windows 10 2004 build 19041.450
 - Version v0.3.10 (assuming this meant version of extension)
 - vscode version 1.48.0

**Additional context**
The files and folders are on the disk, but the extension doesnt display them, even though I created them through the extension.

**Comment by fernandoescolar** [comment]
Hi @OrangeDoggoo,

Would you mind to send me your project file (.XXproj)?
