### ISSUE TITLE
Ability to check for nuget package updates

### ISSUE THREAD

**Issue by miksch123** [fernandoescolar/vscode-solution-explorer#144]
Issue Type: <b>Feature Request</b>

It would be great if you could update nuget packages from within the Solution view. That way I do not need to switch to visual studio every time I want to check for nuget updates. The updates also should fit the framework and version of the solution.  

Extension version: 0.3.11
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

**Comment by fernandoescolar** [comment]
Now you can update automatically your nuget packages in dotnet core projects:

<img width="409" alt="Screenshot 2022-08-17 at 14 14 12" src="https://user-images.githubusercontent.com/3491424/185115871-0f423c0d-234f-4845-a077-a48853449b90.png">

**Comment by miksch123** [comment]
Thanks so much for adding this in. I really appreciate your work there.
