### ISSUE TITLE
Extension shows `--enable-proposed-api` error in the insiders build of VS Code

### ISSUE THREAD

**Issue by ChristopherHaws** [fernandoescolar/vscode-solution-explorer#146]
**Describe the bug**
When I use this extension in the stable build of VS Code, it works fine, however when I use it in the insiders build of VS Code, I get an error message and the solution explorer window is empty.

**To Reproduce**
1. Install the insider build of VS Code
2. Install this extension
3. Open a solution
4. See that you get a toast error with the following text:
```
[fernandoescolar.vscode-solution-explorer]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api fernandoescolar.vscode-solution-explorer
```

**Expected behavior**
No error message would show up and the solution explorer should show the solution and projects as it does in VS Code Stable.

**Screenshots**
![image](https://user-images.githubusercontent.com/5934505/92960680-e538ed00-f422-11ea-857e-e32c622bb128.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Extension Version: 0.3.11
 - VS Code Version: 1.50.0-insiders

**Comment by fernandoescolar** [comment]
Hi @ChristopherHaws 

is it still happening?

**Comment by ChristopherHaws** [comment]
@fernandoescolar I have not seen this happen for a while. Its possible that a VS Code update fixed this issue.

Thanks!
