### ISSUE TITLE
Add ability to visualize the git status of each file, just as the Explorer does

### ISSUE THREAD

**Issue by jselesan** [fernandoescolar/vscode-solution-explorer#154]
I find very useful the ability of view git status of each file in the explorer (green for new files, yellow for non committed files, etc)

It would be nice to have the ability to view the git status in this awesome solution explorer. I know I have the Git Lens plugin, and the integrated git support, but to use them, I need to leave the solution explorer

**Comment by fernandoescolar** [comment]
This is how it currently works.
