### ISSUE TITLE
Unable to delete folders

### ISSUE THREAD

**Issue by mikemcavoy** [fernandoescolar/vscode-solution-explorer#155]
**Describe the bug**
Unable to delete folders in the solution explorer

**To Reproduce**
1. Create a new folder
2. Right click folder
3. Click delete

**Expected behavior**
Expected the selected folder to be deleted

**Screenshots**
<img width="441" alt="Screenshot 2021-01-04 at 19 50 27" src="https://user-images.githubusercontent.com/67292835/103573459-2d928400-4ec6-11eb-865e-c073ce0e7c6b.png">

**Environment (please complete the following information):**
 - OS: Mac
 - Version: 11.1
 - vscode version: 1.52.1

**Comment by zawette** [comment]
same issue on my windows environnement : 
vscode Version: 1.52.1 
OS: Windows_NT x64 10.0.19041
