### ISSUE TITLE
Add C++ Project Templates

### ISSUE THREAD

**Issue by Arc-byte** [fernandoescolar/vscode-solution-explorer#156]
There aren't any C++ language templates. Could that be added?

**Comment by chfilyz** [comment]
Mine cannot include header files

**Comment by fernandoescolar** [comment]
I have not planned any feature related to c++ projects. 
But pull request are welcome :)

**Comment by fernandoescolar** [comment]
More info:

To create new projects, this extension uses dotnet cli to create projects, and the list is populated with the contents of the dotnet new --list command. If you have installed a template for creating vcxproj files, it will be displayed.
