### ISSUE TITLE
Cannot read property 'push' of null

### ISSUE THREAD

**Issue by simdax** [fernandoescolar/vscode-solution-explorer#157]
**Describe the bug**
solution explorer dont find any sln file when multiple files are present in my folder
![image](https://user-images.githubusercontent.com/2458806/104904397-68de8980-5981-11eb-8dd5-32509bf937ed.png)

**To Reproduce**
I open a folder with a lot of .sln. .bff and .mdef files.
I try to refresh solution explorer for him to detect a solution, and it fails

**Expected behavior**
open a specific solution that i would have chosen

**Screenshots**

**Environment (please complete the following information):**
 - Windows 10
 - vscode 1.52.1

**Comment by fernandoescolar** [comment]
Hi @simdax,

Would you mind to send me the .sln files where you have found this issue?
