### ISSUE TITLE
output messy code when i click 'build' buttom

### ISSUE THREAD

**Issue by andycheng-jiuluomall** [fernandoescolar/vscode-solution-explorer#16]
![image](https://user-images.githubusercontent.com/15645427/40535819-c9ae41ba-603c-11e8-89c9-aaecc1ecf203.png)
![image](https://user-images.githubusercontent.com/15645427/40535967-3e776d64-603d-11e8-8cf4-db29e6e39b59.png)
![image](https://user-images.githubusercontent.com/15645427/40535982-47b5466c-603d-11e8-87e5-8ce7ee4e13fd.png)

Windows PowerShell result 
![image](https://user-images.githubusercontent.com/15645427/40536065-873c307a-603d-11e8-9cfa-68a653623d5b.png)

**Comment by fernandoescolar** [comment]
related https://github.com/Microsoft/vscode-arduino/issues/447

**Comment by fernandoescolar** [comment]
Please, could you tell me if v.0.2.26 has solved this problem?

**Comment by andycheng-jiuluomall** [comment]
The problem has been solved 
thanks ~
