### ISSUE TITLE
solution explorer not visible

### ISSUE THREAD

**Issue by mariomuja** [fernandoescolar/vscode-solution-explorer#163]
The solution explorer is not visible although my folder contains a SLN file on top level.

I have installed the extension as described. I am using the most recent version of VSCode. 

What can i do to make the Solution Explorer bar visible?

Thanks a lot for your help,
Mario

**Comment by fernandoescolar** [comment]
Could you check this setting?

```json
"vssolution.showMode": "activityBar",
```

**Comment by mariomuja** [comment]
![2021-03-29_09h30_45](https://user-images.githubusercontent.com/13804419/112801709-80b54680-9071-11eb-90e4-e6f2785c3ff5.png)

Please see the enclosed image. 

The showMode setting has the correct value "activityBar"
(I have not changed any setting after installation of vsCode or the extension). 

In the screenshot, you can also see that my top level folder has a .sln file and that the solution explorer is not visible.

Any other suggestions?

**Comment by fernandoescolar** [comment]
Hi @mariomuja,

Currently it is working fine.

You can set those values in the "Show mode" parameter:
- `activityBar`: it shows a visual studio icon in the left bar. When you click it, it shows the solution explorer panel.
- `explorer`: the solution explorer panel is shown as a tab in the "Explorer" panel.
- `none`: the solution explorer is not going to be shown.

I can see you have configured `activityBar` and the visual studio icon in the left:
![image](https://user-images.githubusercontent.com/3491424/112805582-0f2bc700-9076-11eb-9252-69b0708d3124.png)

**Comment by mariomuja** [comment]
**and the visual studio icon in the left**

thanks for your help! didn't recognize this, because this icon does not appear in your readme.md gifs - I expected to see what you have documented. Please update the gifs/screenshots in readme.md.

**Comment by fernandoescolar** [comment]
I will try. It has been a todo task for a long time :(. Anyway if you want to help me, PRs are welcome :)

Thanks for using my extension and for your help improving it.
