### ISSUE TITLE
Special characters in .csproj file replaced with HTML codes.

### ISSUE THREAD

**Issue by BlueStaggo** [fernandoescolar/vscode-solution-explorer#164]
**Describe the bug**
As soon as I installed the extension and added in a file, Omnisharp gave me an error. I went to look at my .csproj file and it looked like this:
![image](https://user-images.githubusercontent.com/71090710/112751387-ae44b600-8fc5-11eb-82ad-da924e6816e1.png)
I have no idea why the extension did this.

**To Reproduce**
1. Install the extension
2. Add in a new file
3. Your .csproj file is now messed up

**Expected behavior**
I wanted to add in a new file to my project.

**Screenshots**

**Environment:**
 - OS: Windows 10
 - Version 1909
 - vscode version 1.54.3

**Comment by fernandoescolar** [comment]
Thanks for reporting...
It's my fault, yesterday I fixed a bug and I also create a new one.

I'm creating a new version without this behavior...

Sorry!

**Comment by fernandoescolar** [comment]
Please install v0.4.2 to solve this issue,
