### ISSUE TITLE
vssolution.altSolutionFolders no longer respected

### ISSUE THREAD

**Issue by rdewaele** [fernandoescolar/vscode-solution-explorer#165]
**Describe the bug**
The setting I have for `vssolution.altSolutionFolders` seems no longer to be respected.
Where the extension used to show my solution file, it no longer does.

When setting the vscode workspace to the actual directory with the solution file, the extension does pick it up.

**To Reproduce**
Open a workspace where the solution file is located in a `src` subdirectory.

**Expected behavior**
The solution file to be detected.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Version v0.4.2
 - vscode version 1.54.3

**Additional context**

```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.10-arch1-1
```
settings.json includes the following:
```
    "vssolution.altSolutionFolders": [
        "src"
    ],
```

**Comment by peter-job** [comment]
Same issue here

Version v0.4.2
OS: Ubuntu 20.04.2 LTS

VS Code:
```
  Version: 1.55.0
  Commit: c185983a683d14c396952dd432459097bc7f757f
  Date: 2021-03-30T16:01:05.981Z
  Electron: 11.3.0
  Chrome: 87.0.4280.141
  Node.js: 12.18.3
  V8: 8.7.220.31-electron.0
  OS: Darwin x64 20.3.0
```

**Comment by rdewaele** [comment]
Thank you for fixing this promptly. I can confirm the issue is now resolved on my end. :+1:

**Comment by fernandoescolar** [comment]
No problem!
