### ISSUE TITLE
Hover text duplicates item content

### ISSUE THREAD

**Issue by isidorn** [fernandoescolar/vscode-solution-explorer#168]
Hover over an item in the solution explorer.
Notice that the hover text contains the same content as the actual item. This feels like duplication.
I suggest to either not have a hover, or to put some additional information into it to justify it.

![Screenshot 2021-04-09 at 11 07 55](https://user-images.githubusercontent.com/1926584/114157404-e46a2a00-9923-11eb-8c95-331e3d95b54a.png)

**Comment by fernandoescolar** [comment]
Currently it shows the item fullpath, so I going to close it.
