### ISSUE TITLE
Folder view and ability to open existing solution without creating new.

### ISSUE THREAD

**Issue by rodeo22** [fernandoescolar/vscode-solution-explorer#170]
**Is your feature request related to a problem? Please describe.**
Problem statement - Trying to open one repo which is only having folder structure but .Net project and trying to add existing file to folder from default explorer of VS code.

**Describe the solution you'd like**
Solution explorer extension has the ability to provide folder view and also to open existing folder from selected repo without any need to create new at the root.

**Describe alternatives you've considered**
Copies existing file to my project folder from file explorer.

**Additional context**
NA

**Comment by fernandoescolar** [comment]
I think with the latest updates you have a lot of options to open a solution file, so I'm going to close it.
