### ISSUE TITLE
Custom templates support

### ISSUE THREAD

**Issue by Zeon8** [fernandoescolar/vscode-solution-explorer#171]
**Is your feature request related to a problem? Please describe.**
I installed custom project template by `dotnet new -i` but can't use it via vscode solution explorer, because it doesn't show in the templates list.

**Describe the solution you'd like**
I would like to select in template list installed custom template and create project using it.

**Comment by HmWhyNot** [comment]
I also think this would be a nice addition. Could potentially parse the output of "dotnet new -l" to populate the list of templates. Not sure if there's a better way to get that information.
