### ISSUE TITLE
Allow customisation of icons.

### ISSUE THREAD

**Issue by BlueStaggo** [fernandoescolar/vscode-solution-explorer#173]
**Is your feature request related to a problem? Please describe.**
VSCode icons, the icons this extension this uses, don't look great to me.

**Describe the solution you'd like**
Be able to change the icons of the solution explorer. Use the same file icons as the file explorer.

**Describe alternatives you've considered**
You could switch to some other icon pack like Studio Icons. If you don't like that, stick with your preference.

**Additional context**
Here is the problem:
![image](https://user-images.githubusercontent.com/71090710/118153483-dc634580-b40d-11eb-99f1-de84c22006b9.png)
Here is a quick mockup:
![image](https://user-images.githubusercontent.com/71090710/118154159-a07cb000-b40e-11eb-9fd1-f41db655d27f.png)

**Comment by fernandoescolar** [comment]
You can already do it. In the Visual Studio Code settings panel you can look for "Solution Explorer Icons":
![image](https://user-images.githubusercontent.com/3491424/118252970-abd0e980-b4a9-11eb-98b7-01ba9171108e.png)

And them select:
- `solution-explorer`: custom icons from vscode-solution-explorer extension. 
- `mix`: file and folder icons from the installed icons theme. 
- `current-theme`: all icons are from the installed icons theme.

Once you have changed it, remeber reload the Visual Studio Code window:
![image](https://user-images.githubusercontent.com/3491424/118253626-6fea5400-b4aa-11eb-9670-148255945c80.png)

**Comment by BlueStaggo** [comment]
I'll just say that the default setting for this should be `current-theme`.
