### ISSUE TITLE
Can you guys make it work in Linux as well?

### ISSUE THREAD

**Issue by igorrturano** [fernandoescolar/vscode-solution-explorer#176]
I'm using Linux Ubuntu 21.04, and it doesn't work.

**Describe the solution you'd like**
I'd like to be able to use this extension also in my Linux OS.

**Describe alternatives you've considered**
I'm not sure if this is possible, but if it is, that'd be great

**Additional context**
The request is simple, but I'm not sure if it's even possible to achieve.

**Comment by DonThompson** [comment]
What does "doesn't work" mean?  Can you provide more details?
I'm using Zorin, which is built on top of Ubuntu, and it works for me.

**Comment by fernandoescolar** [comment]
Without answer....
