### ISSUE TITLE
Item Nesting

### ISSUE THREAD

**Issue by sanchez** [fernandoescolar/vscode-solution-explorer#178]
Heyo, I love the extension, really helps to improve the dotnet development experience. I would love to see related items being nested within the solution explorer. I have been doing some development Razor Components and CSS Isolation and would for for the CSS items to be nested inside the Razor Component files similar to how Visual Studio does it.

I was wondering if this could just be further applied as a blanket rule, any file which matches the predicate of an existing file in the same folder is automatically nested?

Thanks, Daniel

**Comment by revenz** [comment]
big +1 to this.  just discovered vscode doesnt have this built in.

**Comment by pwshdevops** [comment]
Please make this a thing.
