### ISSUE TITLE
Enable arbitrary .sln location within project

### ISSUE THREAD

**Issue by TaylorEllington** [fernandoescolar/vscode-solution-explorer#180]
In my work context I am often working with solutions generated by CMake, these solutions do not exist at the root of the project.  Instead, these .sln files exist along a path like `project_root/build/bin/windows/x64/project.sln`. This means that when I open the project root in VSCode, the extension does not work.  If I instead target the directory that the .sln lives in, I lose the use of the various CMake extensions that need to be able to see the full project.

I would like to be able to specify a path for the extension to check for a .snl file.

**Comment by fernandoescolar** [comment]
You can add these folders to the following extension parameter to search for .sln files in the desired child folders:

`vssolution.altSolutionFolders`
