### ISSUE TITLE
Look for projects in intermediate child folders

### ISSUE THREAD

**Issue by sharpninja** [fernandoescolar/vscode-solution-explorer#182]
**Is your feature request related to a problem? Please describe.**

My standard project looks like this.

/root
  * Solution.sln
  * src/
    * Project1/
      * Project1.csproj
  * tests/
    * Tests1/
      *  Test1.csproj

This structure does not play nicely with your extension, which seems to rely on the sln file being the direct parent of project files.  

**Describe the solution you'd like**
It would be good to have a configurable list of folders that the plugin would examine to find project files. 

**Describe alternatives you've considered**
None, using `src` and `tests` folders is pretty standard.

**Comment by fernandoescolar** [comment]
You can add those folder to this extension parameter in order to look for .sln files in the child folders you want:

`vssolution.altSolutionFolders`

**Comment by boggylp** [comment]
Yes, but the vs code settings is on the IDE level context. Folder structures can very per project repository, that's why imo this is an improvement request. The settings vssolution.altSolutionFolders is ok for the default, most common folder paths, like 'src' you've mentioned.

**Comment by fernandoescolar** [comment]
I understand your request and I think it could be implemented. But currently you can also make it works using settings for the folder you open with vscode:

- First of all create a folder named ".vscode". 
- Then add a file with the name "settings.json" to this folder. 
- The content of this file could be something like:
```json
{
    "vssolution.altSolutionFolders": [
        "my_special_folder"
    ]
}
```

- Finally reload the window and you can see how it loads the solutions located in `my_special_folder`.

**Comment by sharpninja** [comment]
Doesn't that change where it looks for sln files?  I want it to automatically find csproj files under src/ and tests/

**Comment by fernandoescolar** [comment]
This extension cannot load a single project file. As Visual Studio does, you should include these project files inside a solution. What is different is that if you try to open a project file with VS, it automatically creates a solution that references it. With this extension the solution should be created by yourself.

**Comment by sharpninja** [comment]
What I am referring to is creating a blank solution on cmd line and then opening VSCode.  I believe currently the extension adds existing project files to an empty solution, but they must be in child folder.

**Comment by fernandoescolar** [comment]
Ah, no, no. You should add the projects manually. Even using VS. 

You could open a solution with vscode-solution-extension and add the existing projects:
![image](https://user-images.githubusercontent.com/3491424/133391798-a6c460b6-5455-489c-ad40-5594f45785e5.png)
