### ISSUE TITLE
Shout cut key for "Collapse All"

### ISSUE THREAD

**Issue by babula38** [fernandoescolar/vscode-solution-explorer#185]
**Describe the bug**
Wanted to "Collapse All" to trigger based on the shout cut key, but even after setting the key it never collapse the solution

**To Reproduce**
Set the key binding for "Collapse All" and trigger it.

**Expected behavior**
Should Collapse the solution.

**Comment by fernandoescolar** [comment]
Duplicated #5, I cannot make shortcuts work yet :(
