### ISSUE TITLE
Automatically put correct file extensions for new file + template dialog changes

### ISSUE THREAD

**Issue by little512** [fernandoescolar/vscode-solution-explorer#189]
The flow of putting the filename first, and then the template based on the file extension, is a bit counterintuitive in my opinion. 

![image](https://user-images.githubusercontent.com/23041830/148487945-11954669-b5b9-411a-be26-a5107e75984e.png)

If I were to just put the name "WeatherController" for example, it would put a file named `WeatherController` into my project, which, in my opinion, doesn't make sense and should be the other way around.

![image](https://user-images.githubusercontent.com/23041830/148488290-2cd2308a-9e2b-40a2-ad99-b074fd99721e.png)

Since C# projects generally will only want C# templates, the template dialog should come first based on the project you are adding a file to, and the name (minus the extension) should be suffixed with the proper extension without having to enter it in. IDEs such as Rider and Visual Studio will prompt you for the template first, then the name for the file that template will go into. Similar behavior from this extension would make more sense than the current behavior.

**Comment by pm4rcin** [comment]
You may be interested in checking [csharpextensions](https://github.com/KreativJos/csharpextensions) extension. It is working as you want. I think that this repo should drop support for that so it would be more clean.

**Comment by fernandoescolar** [comment]
I don't think I have ever explained how this function works. It does it in the following way;

The first time you open a solution file in vscode-solution-explorer it will ask you to create the template folder:

![image](https://user-images.githubusercontent.com/3491424/148758572-359d9693-624a-48ca-890f-de13c1813683.png)

If you say "Yes" it will create a folder called ".vscode/solution-explorer" with the following content:

![image](https://user-images.githubusercontent.com/3491424/148758686-a3d0eb96-4c82-4a0e-945e-97baf58e2585.png)

This "template system" is based on the list specified in the ".vscode/solution-explorer/template-list.json" file. It will check the extension you have set in the first step of the new file creation:

![image](https://user-images.githubusercontent.com/3491424/148760131-dab6f094-d564-474e-b5fd-93087ca116ae.png)

And in the second step it will show the templates related to this extension:

![image](https://user-images.githubusercontent.com/3491424/148760236-2545788b-32d1-4f82-9e0b-9c71ca2027be.png)

Once you have selected an option the "template system" will process the new file creation...

**Comment by little512** [comment]
Hi @fernandoescolar, thanks for the reply.

I'm aware of how the extension currently works, but I think it doesn't make sense. I'm making an enhancement suggestion which I think will make the extension better. Let me try to explain exactly why I think it doesn't currently make sense.

When I create a file in a C# project, I expect the dialog to default to C# templates, since that's what would make the most sense to be inserted into a C# project. Having to put the file name I want alongside an extension is extra effort that could be streamlined out of the flow of creating a new file and selecting the template type. Additionally, other IDEs, such as Rider and Visual Studio, already have functionality like I'm describing without the need to put a file extension.

In the [Rider documentation](https://www.jetbrains.com/help/rider/Templates__Applying_Templates__Creating_Files_from_Templates.html), it describes the process of adding a new file to your project, where the steps are as follows: 

![image](https://user-images.githubusercontent.com/23041830/148877455-c8a464b4-dc4f-4390-be09-01c4a7c189bd.png)

As you can see, the templates come first, and the need to put a file extension isn't necessary since the type of file is already known. Further, in Visual Studio, you may also simply select Add -> Class... where the template comes first and the filename comes later. 

![image](https://user-images.githubusercontent.com/23041830/148877697-74a86c86-3dc2-4c94-9cc2-604dc61c2594.png)

I'd love to see this feature be reworked into a more streamlined experience, this extension is very useful otherwise and makes VSCode a more viable option for C# development.
