### ISSUE TITLE
vcxproj support for Add New/Existing Project commands

### ISSUE THREAD

**Issue by pterodattero** [fernandoescolar/vscode-solution-explorer#191]
I'd like to open a C++ project (vcxproj file) or to add one to a solution, as I can do for other project types.

By now, using add existing project command, the prompted file manager does not show vcxproj files, but only 'csproj', 'vbproj', 'fsproj'.
As well, when I use add new project command -> Class library I can only see C#, VB and F# types.

Add support for C++ projects.

**Comment by pterodattero** [comment]
I would like to help, but when I try to debug the extension I get an error this error:

> Activating extension 'fernandoescolar.vscode-solution-explorer' failed: Cannot read property 'map' of undefined.

May you help me?

**Comment by Tpuljak** [comment]
Hi, to workaround this issue, be sure to open a folder inside VSC. If no folder is mounted, the extension can not be activated.

This is something that should be fixed.

**Comment by fernandoescolar** [comment]
I just added `vcxproj` as a known extension in the open projects dialog. 

About creating new projects, this extension uses `dotnet` cli to create projects, and the list is populated with the contents of the `dotnet new --list` command. If you have installed a template for creating vcxproj files, it will be displayed.
