### ISSUE TITLE
Add files to logical folders

### ISSUE THREAD

**Issue by junalmeida** [fernandoescolar/vscode-solution-explorer#192]
**Is your feature request related to a problem? Please describe.**
There is a way to Add and Move projects to logical "folders" on a solution, however there is no way to add existing files into it. 

**Describe the solution you'd like**
Right clicking on an existing folder, it should provide an option to include existing file or create a new one,.

**Describe alternatives you've considered**
Opening the solution file on Visual Studio 2022 and adding files, or manually editing the sln file.

**Additional context**
![image](https://user-images.githubusercontent.com/991675/160669281-a50ef0f8-2f01-4ee1-928d-a0456a30086a.png)

**Comment by callummarshall9** [comment]
This issue https://github.com/dotnet/sdk/issues/9112 may perhaps be related? Because as far as I'm aware not even the .NET CLI currently let's you add solution items?

**Comment by fernandoescolar** [comment]
Currently you can add  a project to the solution and them drag it and drop inside a solution folder.
Or if you are creating a new project, you can specify the folder in the last step...

**Comment by junalmeida** [comment]
@fernandoescolar Not talking about projects, this issue is related to "Solution Files".

**Comment by fernandoescolar** [comment]
In the last version (v0.6.2) you can add existing files to your solution folders. And you can drag and drop them between different solution folders :).
