### ISSUE TITLE
Could not locate info on minimum version of VSCode needed to install vscode-soluton-explorer

### ISSUE THREAD

**Issue by karnrage** [fernandoescolar/vscode-solution-explorer#199]
Hello,

What is the min version of VSCode needed to install your extension?

In the extensions panel when clicking 'Install,' I get the error

"| Error | Couldn't find a compatible version of vscode-solution-explorer with this version of Code

**Comment by fernandoescolar** [comment]
Hi,

For vscode-solution-explorer v 0.4.7, you need at least vscode 1.54.0. You can check it in the package.json file:

https://github.com/fernandoescolar/vscode-solution-explorer/blob/3ecc689aa1c725d190c61a13e2c1a8439886231e/package.json#L23

**Comment by karnrage** [comment]
Thank you.

I can update.

Do you know if any previous versions work with VSCode 1.15.0

Other info:
Date 2017-08-09
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Arch x64

**Comment by fernandoescolar** [comment]
No, I'm sorry... first one was 1.19.0, 5 years ago :

https://github.com/fernandoescolar/vscode-solution-explorer/blame/36ea4faae8e4a1ef49e1ecd30b8750d4c1924cf7/package.json#L23

**Comment by karnrage** [comment]
I'll close the issue. I can update my VSCode

Maybe a low priority is having a version that can work with the 1.15.

Thanks for responding.
