### ISSUE TITLE
File nesting into solution (virtual) folder

### ISSUE THREAD

**Issue by BachiMjavanadze** [fernandoescolar/vscode-solution-explorer#203]
Now VSCode supports file nesting, so instead of this:

![image](https://user-images.githubusercontent.com/38082501/176011782-075f1a81-f516-4802-96a5-43d385e69098.png)

 you can have this (like in Visual Studio IDE):

![image](https://user-images.githubusercontent.com/38082501/176011881-1a1f78ea-babf-4fd1-ab7e-ad8543cec3ac.png)

you just need to add this settings into your settings.json:

`"explorer.fileNesting.patterns": {
    "*": "${basename}.*.${extname}"
}`

all file nesting patterns: https://github.com/antfu/vscode-file-nesting-config

Please add this feature into the solution (virtual) folder:

![image](https://user-images.githubusercontent.com/38082501/176012772-2dfa81f8-2838-4955-8736-b4a6a15e9975.png)

**Comment by loligans** [comment]
Came here to add the same request and found it has already been requested :sunglasses: here's my :+1:

**Comment by fernandoescolar** [comment]
Currently you can nest files with the following pattern: `{name}.*.{extension}` modifying `vssolution.itemNesting` parameter in your vscode settings.

**Comment by BachiMjavanadze** [comment]
@fernandoescolar `vssolution.itemNesting` takes only 2 parameters: true or false. How can I pass `{name}.*.{extension}` parameter?

**Comment by fernandoescolar** [comment]
Currently, this expression is not supported, only the preconfigured pattern...

**Comment by BachiMjavanadze** [comment]
problem is solved with the setting:

`"vssolution.itemNesting": true,`
