### ISSUE TITLE
Error: "command 'solutionExplorer.refresh' not found"

### ISSUE THREAD

**Issue by bravikov** [fernandoescolar/vscode-solution-explorer#22]
Error after press 'Refresh' button.

- Ubuntu 16.04
- VS Code 1.24.1
- vscode-solution-explorer 0.2.29

**Comment by arjen1984** [comment]
Error also happens in MacOS High Sierra with VS Code 1.26.0 with vscode-solution-explorer 0.2.32

**Comment by fernandoescolar** [comment]
I'm not sure about this issue, but maybe it has been solved in the v.0.2.33. In this version the "Solution Explorer" panel is not showed before the extension have been loaded.
