### ISSUE TITLE
ID 为 d:\xxx.sln[solution]-Modules[solution-folder]-xxx[project]-Common[project-folder] 的元素已被注册

### ISSUE THREAD

**Issue by elvismile** [fernandoescolar/vscode-solution-explorer#222]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - vscode version [e.g. 1.42]

**Additional context**

**Comment by HaoZhiYing** [comment]
How to solve this problem
