### ISSUE TITLE
Remove Indent Guides in Solution Explorer

### ISSUE THREAD

**Issue by BachiMjavanadze** [fernandoescolar/vscode-solution-explorer#228]
Please add ability to remove Indent Guides:

![image](https://user-images.githubusercontent.com/38082501/195679150-6aa5bd49-2d8b-41cb-80b7-70f269d6d32b.png)

settings for regular explorer:

`  "workbench.tree.renderIndentGuides": "none",`

**Comment by fernandoescolar** [comment]
You can already hide the ident guides (settings -> Workbench -> Appearance -> Tree: Render Ident Guides):

![Screenshot 2022-10-14 at 09 48 49](https://user-images.githubusercontent.com/3491424/195792163-a10c2959-7dbe-4603-b6df-3c1e520586e4.png)

**Comment by BachiMjavanadze** [comment]
@fernandoescolar 
I know that I can do it in regular explorer, I wrote the peace of `settings.json` code:

`"workbench.tree.renderIndentGuides": "none"`

but I need it in regular explorer. I want to remove this lines only in `solution explorer` like in `Visual Studio IDE`.

**Comment by fernandoescolar** [comment]
Currently this feature is handled for all treeviews and there is no extension point in the vscode-api to do it in a custom treeview :(

https://code.visualstudio.com/api/references/vscode-api#TreeDataProvider
