### ISSUE TITLE
NodeJS project type not supported

### ISSUE THREAD

**Issue by FabianTe** [fernandoescolar/vscode-solution-explorer#23]
The extension is unable to open NodeJS projects (`.njsproj` files)

It would be nice if this would work.

Also it would be a nice workaround if the extension displayed unknown project types as regular folder. Is this possible?

**Comment by CatGirlsAreLife** [comment]
It would be even better if we could just extend this extension ourselves to add the project types we want. Then just install the extensions to this extension. 🤔 But can it be done though?

**Comment by fernandoescolar** [comment]
You can create a Pull Request :)
