### ISSUE TITLE
Language of the OS

### ISSUE THREAD

**Issue by ShalokShalom** [fernandoescolar/vscode-solution-explorer#231]
**Describe the bug**

**To Reproduce**
1. Use language X on your OS
2. Use language Y within VSCode
3. Experience VSCode and all extensions using Y
4. See that vscode-solution-explorer uses X in some parts:

**Screenshots**
![Screenshot_51](https://user-images.githubusercontent.com/6344099/196684754-78262721-4e68-4149-9745-0a51b4977c71.png)

German results in English VSCode and German Garuda Linux. 

Klassenbibliothek = Class library
Konsolenapp = Console App

**Environment (please complete the following information):**
 - OS: Garuda
 - Version rolling
 - vscode version 1.72.2

**Additional context**

**Comment by fernandoescolar** [comment]
1. Currently this extension does not support multiple languages :(
2. To get the list of project types and other tasks, vscode-solution-explorer internally executes `dotnet` commands. In this case it is this: `dotnet new list` so it makes sense to get some literals in the `X` language.

**Comment by ShalokShalom** [comment]
Could we this reset to use English all over the place, instead?

**Comment by fernandoescolar** [comment]
It runs a command on your machine, it can't manage the language... 
and I wouldn't want to hard code the list of project types as you can have different project templates installed...
