### ISSUE TITLE
Not able to change casing when renaming file

### ISSUE THREAD

**Issue by lewiuberg** [fernandoescolar/vscode-solution-explorer#238]
**Describe the bug**

Not able to rename a file if the name is the same and only the casing has changed.

**To Reproduce**

1. Select a file in Solution Explorer.
2. Richt click and select `Rename`.
3. Change the filename. i.e. `ContactRepositorySp.cs` to `ContactRepositorySP.cs`

**Expected behavior**

The filename gets renamed.

**Current behavior**

The file is not renamed and a warning states that `File already exists`

**Screenshots**

![Skjermbilde 2022-12-08 kl  14 33 30](https://user-images.githubusercontent.com/43423020/206459498-14d78b0d-285e-4c99-95d5-286ab708a387.png)

**Environment:**
 - OS: macOS
 - Version 13.0
 - vscode version 1.73.1

**Comment by badsyntax** [comment]
Added a PR for this here: https://github.com/fernandoescolar/vscode-solution-explorer/pull/241
