### ISSUE TITLE
Expand Not Working in Solution Explorer

### ISSUE THREAD

**Issue by sharperDev2112** [fernandoescolar/vscode-solution-explorer#239]
### Description
I click on a folder in the solution explorer but the files never show

### To Reproduce
1. Load .Net Core solution in VS Code and wait for solution to render
2. Click folder under solution and wait for it to expand

### Expected behavior
I expect the caret on the left of the folder to point down, 
I expect the "loading indicators" or spinner to display while the file list loads
I expect the spinners to stop and the files to appear
The loading indicators do not load and the files do not appear for certain projects

### Screenshot Enclosed
It shows the MIG.Preferences.Infrastructure project with the downward caret icon which I clicked on but the files (shown above in file explorer) never show up

### Environment
 - OS: Windows 10 Pro
 - Extension Version: 0.7.4
 - vscode version: 1.74.0

### Additional Info
This does not happen for other developers with same versions as far as I can tell.  It happens for me in different solutions though - some .net core 3.0 and some in .Net 6.0
![WontOpen](https://user-images.githubusercontent.com/48840739/207144903-747d2583-7d6d-4854-802d-539929aaed8f.png)

**Comment by badsyntax** [comment]
I've added a PR that might fix this: https://github.com/fernandoescolar/vscode-solution-explorer/pull/240
