### ISSUE TITLE
Reveal file in solution

### ISSUE THREAD

**Issue by badsyntax** [fernandoescolar/vscode-solution-explorer#244]
**Is your feature request related to a problem? Please describe.**

When I use cmd+p to select a file, the file is not shown in the solution explorer, and there's no option to "Reveal file in solution explorer"

**Describe the solution you'd like**

Whenever I select a file, I'd like the file to be highlighted in the solution explorer. Alternatively, I'd like a command (like a file context menu option) to be able to "Reveal in solution explorer"

**Additional context**

Auto-revealing a file in the solution explorer is the default behaviour on VS on Mac.

**Comment by fernandoescolar** [comment]
The command name is "Solution Explorer: Select Active Document"

![select-active-item](https://user-images.githubusercontent.com/3491424/208719326-5cc687a6-6b2c-49bd-be36-8b16b63c0999.gif)
