### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by fadhly-permata** [fernandoescolar/vscode-solution-explorer#25]
Hi Fernando,

It's me again (with another problem again).

On my Dell laptop, I've got error message `Cannot read property 'forEach' of undefined` popping up when I am expanding (or refreshing) the solution from the treeview. This error message only appears when I am enabling your extension, and this error appears on any solution files.

As additional info, my laptop specs are Dell Latitude E6420:
- 64-bit Windows 10
- Intel Core i5-2520M - 2.50GHz (up to 3.20GHz with Turbo Boost mode enabled)
- 4Gb of RAM
- Develop the project using C# MVC ASP.Net, with lot ecmascript6 file (but saved as a *.js file extension) inside the solution.
- The Solution file created using VS2017 Community Edition
- VSCode v1.24.1
- vscode-solution-explorer v0.2.29

I don't know these error raised by invalid of my os configurations, hardware specs, or any else. I've tried to research on this problem, it seems (not sure) the problem is on VSCode core engine.

Can you help me with this problem?

---

P.S:
- This message never appears on my Lenovo laptops.
- Sorry for my bad English.

**Comment by naveed-butt** [comment]
Hi,
I opened an issue for VS Code. Looks like it is an issue with this and the above mentioned one...
[https://github.com/Microsoft/vscode/issues/53088#issuecomment-401891157](https://github.com/Microsoft/vscode/issues/53088#issuecomment-401891157)

Please have a look.
Regards,
Naveed Butt

**Comment by fernandoescolar** [comment]
It seems a problem reading the project file. Have you tried to reinstall the extension?

Note. I have added a condition to check if you are working with non expected xml formats.

**Comment by fadhly-permata** [comment]
Hi Naveed, 
Thanks for your comment. Yeah, I feel (still not sure) the problem raised by VSCode core engine.

---

Fernando,

> It seems a problem reading the project file. Have you tried to reinstall the extension?

Yes, even I have re-install the VSCode too using the latest version (1.25.0), but the problem still raised. 

---

> Note. I have added a condition to check if you are working with non expected xml formats.

Because I've got this problem (as I've [reported before](https://github.com/fernandoescolar/vscode-solution-explorer/issues/15)), So I've tried to copy the solution into my another laptop. The solution is fetched perfectly on the solution explorer. Since my another laptop (Lenovo) almost offline, so I am used old version off VSCode & extensions.

**Comment by Zonnery** [comment]
The problem is still here
```
notificationsAlerts.ts:40 Error: Cannot read property 'forEach' of undefined
	at project.elements.forEach.element (C:\Users\esmirnov2\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.30\out\model\Projects\Kinds\StandardProject.js:297:33)
	at Array.forEach (native)
	at StandardProject.parseDocument (C:\Users\esmirnov2\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.30\out\model\Projects\Kinds\StandardProject.js:295:26)
	at new StandardProject (C:\Users\esmirnov2\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.30\out\model\Projects\Kinds\StandardProject.js:34:18)
	at Function.<anonymous> (C:\Users\esmirnov2\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.30\out\model\Projects\ProjectFactory.js:48:20)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\esmirnov2\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.30\out\model\Projects\ProjectFactory.js:4:58)
	at <anonymous>
```

**Comment by fernandoescolar** [comment]
It's confusing, I had added these lines before "project.elements.forEach":

```
 if (!project) project = { elements: [] };
 if (!project.elements || !Array.isArray(project.elements)) project.elements = [];
```

**Comment by fadhly-permata** [comment]
Hi Fernando,

FYI, after updating your latest version (0.2.32) the error message not popping up anymore. Have you fixed this problem? If so, you can close my issue :)

Thank you very much

**Comment by ababilone** [comment]
Hi,

I had the same issue before I realize that I had in my solution a project with an empty ItemGroup.

Looks like CpsProject.parseDocument is not protected for that.

Error has gone once I have removed the empty ItemGroup.

Hope this help.

**Comment by SilentCC** [comment]
Hi ,
I met the same problem with the latest version.
