### ISSUE TITLE
Output tab spam

### ISSUE THREAD

**Issue by Nachtwind85** [fernandoescolar/vscode-solution-explorer#250]
Hi, 

This may be related to https://github.com/fernandoescolar/vscode-solution-explorer/issues/177 

Steps to reproduce:
- Just open any file in the solution explorer
- Output tab shows "Open file ... in preview"

Expected behavior:
- Not that message ;) 

Since i work a lot with the Terminal and Debug consoles this is highly irritating that the tab switches to Output each time i click on an object. 
Since i havent found a switch to turn this off and it feels like Issue 177 i think this may be a bug rather than a feature..

Cheers
Martin

**Comment by badsyntax** [comment]
I think the switch you're looking for `"vssolution.showOutputChannel": false` (although i agree i think the default should be `false`)

**Comment by Nachtwind85** [comment]
Unfrtunately that is already set to false.
