### ISSUE TITLE
Create New Solution Button Not Working

### ISSUE THREAD

**Issue by sarapayne** [fernandoescolar/vscode-solution-explorer#264]
The create solution button is not working. I have the same issue in both Linux and Windows 11. 

Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Everything else works; creating a new solution from the command line is recognised and opens. 

Steps to reproduce. 

1. Clean install of Vs-Code with no extensions. 
2. Add in the C# for Visual Studio Code (powered by OmniSharp) extension
3. Add in the vscode-solution-explorer extension. 
4. Create a new folder
5. Open the folder in vs code. 
6. Click on the solution button in the bottom left. 
7. Click on the "Create New Solution" button - nothing happens. 
8. Open the command pallet and run Solution Explorer: Add Solution File - nothing happens, and it is shown as recently used. 

I have tried turning sandboxing on and off as well as trusted folders, and I have the same issue regardless of the status of either setting. Additionally I have the same issue in Ubuntu and Windows 11.

**Comment by qsgy** [comment]
https://user-images.githubusercontent.com/19835928/220304845-d855fadc-0859-4608-964d-7a301506aae0.mp4

我也一样，不起作用
