### ISSUE TITLE
Cursor is not placed in a file 

### ISSUE THREAD

**Issue by toughtcrime** [fernandoescolar/vscode-solution-explorer#277]
#267 
Previously I created enhancement [issue](https://github.com/fernandoescolar/vscode-solution-explorer/issues/267).  I know that is stupid and this is my fault that I didn't write much more detailed how it should looks like.

Everything works fine except only 2 things:
 
1.After pressing enter button, focus should leave solution explorer and place cursor in a file, but it doesn't happen.
2. After pressing shortcut Ctrl + Alt + L for focus and then it should leave focus., 
I will attach some examples in gif how it should work and how it works for clear understanding where I press shortcut for focus and leave focus **Ctrl + Alt + L** and pressing Enter button for going to a file.

1. Here the example how it works.
![2. How it works](https://user-images.githubusercontent.com/24855345/227787607-e8f76a6b-78e4-493c-9543-e6ec444bb4f0.gif)

2. Here the example how I suppose should work
![how should look like](https://user-images.githubusercontent.com/24855345/227787972-1c16e93e-a98f-4749-bca9-b85484a1380b.gif)

**Comment by fernandoescolar** [comment]
from v0.8.5 you can open a file using "ctrl+enter" and them it will focus the document
