### ISSUE TITLE
Future of the `vscode-solution-explorer` extension

### ISSUE THREAD

**Issue by fernandoescolar** [fernandoescolar/vscode-solution-explorer#290]
Dear `vscode-solution-explorer` users,

I hope this message finds you well. I have an important decision to make regarding the future of the `vscode-solution-explorer` extension, and I value your input and feedback in this process.

As you may know, Microsoft is currently developing an official extension ([C# DevKit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit), [more information](https://code.visualstudio.com/docs/csharp/project-management)) that aims to provide similar functionality within Visual Studio Code. Considering this development, I am reaching out to you, the dedicated users of `vscode-solution-explorer`, to gather your thoughts and insights on whether it makes sense to continue with the development of our extension.

I want to ensure that our efforts align with the needs and preferences of the community, and your input will play a crucial role in shaping the future of this project. Your perspective is invaluable to me, and I genuinely appreciate your participation in this decision-making process.

To help guide the discussion, I would appreciate your thoughts on the following questions:

- **Value and Functionality**: Do you believe that the existing `vscode-solution-explorer` extension provides unique value or functionality that is not covered by the upcoming official extension from Microsoft?

- **User Base**: How many users do you estimate will continue to rely on the `vscode-solution-explorer` extension, even with the availability of the official extension?

- **Maintenance and Support**: Are you willing to contribute to the maintenance and support of the `vscode-solution-explorer` extension, either through code contributions, bug reports, or feature requests?

Please take a moment to share your thoughts, suggestions, and any other relevant feedback regarding the future of the `vscode-solution-explorer` extension. I highly value your opinion and want to ensure that I make an informed decision that best serves the community's needs.

Thank you for your continued support, engagement, and dedication to the `vscode-solution-explorer` project. I look forward to hearing from you and working together to determine the best path forward.

Warm regards,
Fernando Escolar

**Comment by spouliot** [comment]
I'm not sure if this applies to many of your users but VSCodium (and non-official builds of VSCode, like gitpod uses) won't be able to use the MS extension.

Thanks for your efforts!

**Comment by eduardomezencio** [comment]
It's important to remember this new microsoft extension is not open source, so I won't be using it, and I think this applies to many others. They also probably don't intend to make it so, considering they developed it as a new extension instead of simply adding the functionality to the existing MIT licencesed C# extension (this is just my opinion, of course).

**Comment by Xylobol** [comment]
Hello! I'd like to echo the above sentiment. I really would like to thank you for your work on this, and I understand if you stop working on this, but I'd really like to highlight that this is important for those who don't use upstream VS Code or want to use their official extension for whatever reason.

**Comment by BachiMjavanadze** [comment]
> It's important to remember this new microsoft extension is not open source, so I won't be using it, and I think this applies to many others. They also probably don't intend to make it so, considering they developed it as a new extension instead of simply adding the functionality to the existing MIT licencesed C# extension (this is just my opinion, of course).

`The move of the repo and open sourcing of the extension code will take place in one week, on June 13`
[LINK](https://github.com/dotnet/vscode-csharp/issues/5708#:~:text=The%20move%20of%20the%20repo%20and%20open%20sourcing%20of%20the%20extension%20code%20will%20take%20place%20in%20one%20week%2C%20on%20June%2013)

**Comment by Igorgro** [comment]
I thinlk you can try to contribute solution explorer to new open-source C# extenison (open PR), and see how they will react. Personally, I also do not intend to use proprietary DevKit extansion

**Comment by Xylobol** [comment]
> > It's important to remember this new microsoft extension is not open source, so I won't be using it
> 
> `The move of the repo and open sourcing of the extension code will take place in one week, on June 13` [LINK](https://github.com/dotnet/vscode-csharp/issues/5708#:~:text=The%20move%20of%20the%20repo%20and%20open%20sourcing%20of%20the%20extension%20code%20will%20take%20place%20in%20one%20week%2C%20on%20June%2013)

This seems to only be for the language server. I've read it as saying that the solution/test explorer are proprietary - we'll see in a few days.

**Comment by liquiad** [comment]
The new C# Dev Kit does not support many legacy .NET project types, so there is still much use for this extension.

**Comment by eduardomezencio** [comment]
> > It's important to remember this new microsoft extension is not open source, so I won't be using it
> 
> `The move of the repo and open sourcing of the extension code will take place in one week, on June 13` [LINK](https://github.com/dotnet/vscode-csharp/issues/5708#:~:text=The%20move%20of%20the%20repo%20and%20open%20sourcing%20of%20the%20extension%20code%20will%20take%20place%20in%20one%20week%2C%20on%20June%2013)

https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_is-c-dev-kit-open-source-why-not

**Comment by pm4rcin** [comment]
I'll post some numbers. Number of installation of .NET extensions from open-vsx.org:
- free-omnisharp-vscode 71,979
- C# Extensions                   8,344
- Code Butler                       1,517
- MSBuild project tools      1,582
- Roslynator                            300
- vscode-solution-explorer 3,951
- Nuget Gallery                    2,594

I'm not counting installations via official vscode Marketplace because I don't think people who use vscode care about free software (not to be confused with open source) that much and also because the proprietary extension would probably be better for them as you mentioned.

So looks like that this extensions is one of the most popular from .NET category in VScodium and similar editors and has value for people using it. It's just raw numbers so anyone could form an opinion. That's my 2c.

**Comment by RivenSkaye** [comment]
Downloads on Open VSX are still going up. I use this a lot as well, even at work due to the _horrible_ licensing scheme M$ uses.
Besides that, I try and grab as many FLOSS extensions as possible, even though I run binary blobs of VSC on some of my machines.

If you decide to stop maintaining this in favor of the official extension provided, that'd be a massive loss once it stops working.

**Comment by tygore587** [comment]
Another point to have your extension: The official C# Dev Kit extension is not free to use for enterprises. You need to have a visual studio professional or enterprise license for it.

**Comment by lixaotec** [comment]
> C# Dev Kit extension i

my 2 cents , indeed charged, but they have eased small team up to 5 
![image](https://github.com/fernandoescolar/vscode-solution-explorer/assets/40803484/14d71a0f-43ea-4a6c-b7e1-da54a8c8075d)

https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq

**Comment by tats-u** [comment]
C# Dev Kit is really just trash for most companies.
Who on the earth pays for that very expensive VS subscription for that extension instead of the perpetual license of VS Pro?
Microsoft is really stupid.
You do not have to stop maintaining this project at all.

**Comment by eduarddejong** [comment]
> C# Dev Kit is really just **_trash_** for most companies. Who on the earth pays for that very expensive VS subscription just for that extension instead of the perpetual license of VS Pro? Microsoft is really stupid. Most of those who use VS Code instead of VS to develop C# apps have not been subscribed in the VS subscription. Some of them do not use Windows and cannot install VS. You do not have to stop maintaining this project at all at least until Microsoft starts selling more economical and smaller licenses. This extension and Ionide F# are friends of employees of companies that have only perpetual or no licenses of VS.

Even with a low price or being free of any cost cannot defeat the value of Free and Open Source software.
It's not about money, it's about collaboration, transparency and freedom. And so much more.

**Comment by bicijinlian** [comment]
官方扩展在于大一统一，所有功能全放一起。目前感觉，些扩展比官方好用的多。特别是很符合VS的习惯。

**Comment by alex-jitbit** [comment]
Now that C# Dev Kit stopped working in Cursor you should expect more users switching to your tool instead of C# Dev Kit
