### ISSUE TITLE
Archive Repo

### ISSUE THREAD

**Issue by ChaseKnowlden** [fernandoescolar/vscode-solution-explorer#292]
https://devblogs.microsoft.com/visualstudio/announcing-csharp-dev-kit-for-visual-studio-code/#manage-your-projects-with-a-new-solution-view

See #290.

**Comment by pm4rcin** [comment]
@Bomret but only for people using official proprietary distribution of vscode... :(

**Comment by Bomret** [comment]
Oh wow, I totally flipped what I wanted to say. “This extension has more features than the dev kit extension” was what I had intended. Should have read my own stuff before posting 😄

**Comment by RivenSkaye** [comment]
This extension also provides support without the constant nagging about logging in to an M$ account for features tied to available VS licenses.
Please don't archive this

**Comment by ChaseKnowlden** [comment]
Thank you @RivenSkaye.
