### ISSUE TITLE
Element with id is already registered

### ISSUE THREAD

**Issue by ThaDaVos** [fernandoescolar/vscode-solution-explorer#294]
**Describe the bug**
It used to occur sometimes (Mostly after adding nuget packages) but now I can't even view my project - it keeps showing an error message with `Element with id {INSERT_ID} is already registered` and it won't unfold the project.

Sometimes I can get it working by folding/unfolding and using the refresh button multiple times

**To Reproduce**
1. Go to solution explorerer
2. Click on try to unfold your project
3. See error

**Expected behavior**
Unfolds the project

**Screenshots**
![afbeelding](https://github.com/fernandoescolar/vscode-solution-explorer/assets/5251028/60fc3c84-db7d-4805-89d2-7f94c0f442ee)
![afbeelding](https://github.com/fernandoescolar/vscode-solution-explorer/assets/5251028/5a96ac7a-6508-4a82-bc55-deac85547430)

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Version [e.g. 22] ?
 - vscode version [e.g. 1.42] 1.80.2

**Additional context**

**Comment by Yannis-S-Standaert** [comment]
I have the same issue (using cursor ai, an ide based on vs code)

**Comment by fernandoescolar** [comment]
Duplicated #274
