### ISSUE TITLE
Syntax coloring for `.sln` files

### ISSUE THREAD

**Issue by geekley** [fernandoescolar/vscode-solution-explorer#295]
**Is your feature request related to a problem? Please describe.**
I believe .sln files don't currently have syntax highlighting in VSCode (I assume even in C# Dev Kit, which I don't and can't use).

**Describe the solution you'd like**
Please add simple syntax coloring for `.sln` files.
Should be easy enough to make a `tmLanguage` syntax file or modify the one linked below.
It should support at the bare minimum strings and comments.
Then preferably keywords and operators as well, like `=` `|` `.` and `Project`/`EndProject`, the header, etc. And GUIDs.

If you want to go further than just syntax, you could also provide a "goto definition" for project GUIDs to their definition lines and from the path there linking to the corresponding `.XXproj` file.

**Describe alternatives you've considered**
Interpreting it as .ini or .properties isn't quite the right syntax.

**Additional context**
[VSCode Guide: Syntax Highlighting](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide)
[This grammar](https://github.com/Nixinova/NovaGrammars/blob/main/grammars/solution.yaml-tmLanguage) is what GitHub uses. It's not perfect IMO, but it's a great start.
The [spec](https://learn.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file)?
[VSCode Guide: Provide Definitions of a Symbol](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#show-definitions-of-a-symbol)

**Comment by eduarddejong** [comment]
Currently I am just combining this extension with one that I already used before, which turns out to still work without any issues:
https://marketplace.visualstudio.com/items?itemName=logerfo.sln-support
It's a very simple one. But I think there there are some other extensions too.

However having this feature would be really great.

Still a lot of thanks for making this really useful - **open source** - extension.

**Comment by geekley** [comment]
Thanks! I left some review comments in the commit suggesting improvements.

There's also [the grammar from this extension](https://github.com/TobiasSekan/SolutionExtension/blob/main/syntaxes/sln.tmLanguage.json) which appears to be quite comprehensive - though you can't just copy it because it uses AGPL license, it might still be useful for learning and to catch potentially missing grammar rules.
