### ISSUE TITLE
Ctr+Enter hotkey should have a "when" condition to not mess with other hotkeys

### ISSUE THREAD

**Issue by adalisk-emikhaylov** [fernandoescolar/vscode-solution-explorer#296]
**Describe the bug**
This extension registers a <kbd>Ctrl</kbd><kbd>Enter</kbd> hotkey (`solutionExplorer.openFileAndFocus`), but doesn't set a `when` condition for it. This breaks this key combination in other places, such as "create commit" when inputting a commit message.

**To Reproduce**
1. Go to the "source control" tab in a git repo.
2. Type in some message.
3. Press <kbd>Ctrl</kbd><kbd>Enter</kbd>, observe nothing happening.
4. Disable this extension and try again, and you should see a commit being created.

**Expected behavior**
The <kbd>Ctrl</kbd><kbd>Enter</kbd> hotkey should have a `when` condition (that disables it at least during commit message editing).

**Environment:**
 - OS: Windows 10
 - vscode version 1.85.1

**Comment by jibbers42** [comment]
This also seems to affect `Insert Line Below` (determined by extension bisect feature). The command is `Solution Explorer: Open File`, so it seems like it should only be enabled if the Solution Explorer has focus if possible (I may be misunderstanding the feature).

I may have missed it, but a setting to disable this feature completely would be appreciated.

For now I've added the following to my `keybindings.json` to disable and `Insert Line Below` is now working again...
```json
    {
        "key": "ctrl+enter",
        "command": "-solutionExplorer.openFileAndFocus"
    }
```
