### ISSUE TITLE
Keyboard shortcuts conflict

### ISSUE THREAD

**Issue by sig00x** [fernandoescolar/vscode-solution-explorer#299]
**Describe the bug**
When I enable this extension, ctrl+Enter does not insert line bellow the current line anymore. When I disable the extension everything works as expected. The shortcut list for ctrl+Enter looks the same with extension being on and off.

**Environment (please complete the following information):**
 - OS: Windows 10
 - vscode version: 1.86

**Comment by fernandoescolar** [comment]
duplicate #296
