### ISSUE TITLE
Solution explorer crash with no error message

### ISSUE THREAD

**Issue by Xarkam** [fernandoescolar/vscode-solution-explorer#30]
hi.

After I test to correctly configure solution explorer (#29), I discover the extension crash with no error in developer tools.

My configuration into general settings (not workspace):
```
"vssolution.showMode": "activityBar",
"vssolution.solutionExplorerIcons": "current-theme"
```

With this, I click on solution explorer in explorer and the selution explorer panel disappear.

I've no logs anything with error from this extension.

**Comment by fernandoescolar** [comment]
related: #28
