### ISSUE TITLE
`ctrl+enter` keybinding conflicts with default source control

### ISSUE THREAD

**Issue by woter1832** [fernandoescolar/vscode-solution-explorer#302]
**Describe the bug**
Please review issue [#214319](https://github.com/microsoft/vscode/issues/214319) raised in Microsoft/VSCode repository.

Thanks.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - vscode version [e.g. 1.42]

**Additional context**

**Comment by fernandoescolar** [comment]
duplicate #296
