### ISSUE TITLE
Unable to load solutions from folder that contains multiple solution (.sln) files

### ISSUE THREAD

**Issue by kanstey** [fernandoescolar/vscode-solution-explorer#33]
In our environment, we store our solutions in a single folder in source control.  I was able to get vscode solution explorer to work perfectly when I opened a folder in VSCode that contained a single solution file.  However, when I attempted to open a folder that contained multiple solution files, it did not locate any of the solutions.

Any help would be appreciated.

**Comment by fernandoescolar** [comment]
I can not reproduce this issue. Would you mind to send me more details?
