### ISSUE TITLE
Unknown project type for VS2017 projects

### ISSUE THREAD

**Issue by cpadilla** [fernandoescolar/vscode-solution-explorer#40]
I'm seeing "Unknown Project Type" for my files when I try to use this extension.

Attached is one of my .vcxproj files (renamed to .txt extension so I could upload it). It might be possible that it doesn't recognize 2017 solution files.

![issue](https://user-images.githubusercontent.com/1704172/45889411-61e1e500-bd8e-11e8-80f9-2dd1161d7b60.PNG)
[WarpEngine.txt](https://github.com/fernandoescolar/vscode-solution-explorer/files/2405901/WarpEngine.txt)

**Comment by juanro49** [comment]
Same problem for me with projects in c++ languaje builded in VS 2017

**Comment by fernandoescolar** [comment]
Duplicate #19
