### ISSUE TITLE
Cannot see the changes/diff from the built in Source control

### ISSUE THREAD

**Issue by MatraiMilan** [fernandoescolar/vscode-solution-explorer#41]
#### Requirements:
- vscode-solution-explorer is installed
- there are some local changes that could be commited

#### When:
- the user clicks on one of the changes under *Source control* menu to see the diff

#### Explected:
- the focus/side menu stays at the selected file and the built-in diff view opens

#### Bug:
- the side menu jumps to the *Solution explorer* and selects the file with or without opening the diff view

#### Environment:
- Ubuntu 18.04
- VsCode 1.27.2

**Comment by HuNHuNt3r** [comment]
I also experienced this and an additional bug:
If I search in files (ctrl + shift + f) and then I click on a result from the list, it jumps to the Explorer window (and shows the content of the files). But it shouldn't switch view, it should stay on the Search window so I am able to switch between the results quickly!
After I disabled this vscode-solution-extension, everything works fine.

**Comment by MatraiMilan** [comment]
Setting `vssolution.trackActiveItem` to `false` helped me as well! Thank you very much! 
I close the issue!
