### ISSUE TITLE
Solution Explorer won't stay disabled

### ISSUE THREAD

**Issue by ruant** [fernandoescolar/vscode-solution-explorer#44]
Issue Type: Bug

- Open up some files so there are some in the tab.
- Right click, uncheck solution explorer from the left pane.
- Change to a new tab.
- Solution explorer is active again.
- Change back to the tab that you disabled solution explorer on, active there too.

https://github.com/Microsoft/vscode/issues/60093

**Comment by fernandoescolar** [comment]
#49 related
