### ISSUE TITLE
Cannot see 'solution explorer' in explorer panel MacOS

### ISSUE THREAD

**Issue by DeanForde** [fernandoescolar/vscode-solution-explorer#45]
I have installed the extension vscode-solution-explorer however I noticed that the solution explorer does not stay present in the explorer panel, for instance If I open an empty workspace I cannot see solution explorer until I open some sort of file, then and only then will the solution explorer appear,  therefor if I want to create a new project through VS code I have to open an old project for the solution explorer to appear and then right click on solution explorer to create a new project, I cannot understand why it does not stay present? also support for creating c++ console apps would be amazing

**Comment by fernandoescolar** [comment]
Could you check this setting?

```
"vssolution.showMode": "activityBar",
```
