### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by buinauskas** [fernandoescolar/vscode-solution-explorer#5]
Would it be possible to add keyboard shortcuts to Solution Explorer, such as:
 - Delete
 - Rename
 - Add new file
 - Copy
 - Paste
 - Others

**Comment by onbkts** [comment]
Hi, I'm that person who have given 4 stars to your extension on its Visual Studio Code page. It doesn't work when context menu is visible either. This extension has a future and I appreciate all of your work on the issues.

**Comment by avin-shum** [comment]
Hi, even the context menu is visible, the keys are not working.

Extension version: 0.3.2
VSCode version:

> Version: 1.33.1
> Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
> Date: 2019-04-11T08:27:14.102Z
> Electron: 3.1.6
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 6.1.7601

**Comment by asteinba** [comment]
This issue still persists on v0.4.3

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.13-200.fc33.x86_64
```
