### ISSUE TITLE
Find sln files in multi-root workspace

### ISSUE THREAD

**Issue by mcdevmc** [fernandoescolar/vscode-solution-explorer#50]
I have a vscode workspace with multiple root directories, each containing a single solution file at the root.  The solution explorer is only finding the solution file in the top directory, and there is no way for me to add the solution from the second root directory to the explorer.

**Comment by vlesierse** [comment]
@mcdevmc This could be solved by this PR - #38 Support for Workspaces
So for I didn't receive any feedback...

**Comment by julichan** [comment]
I'd like one too as well. Can't use the extension until this is donc. thanks

**Comment by AbbyDeng** [comment]
same here, I'm investigating in my company to use Visual Studio Code with this extension you guys have been working on (btw thanks a lot for this extension!), here's the screenshot:
![image](https://user-images.githubusercontent.com/8296117/69271781-5ce31600-0b8a-11ea-9630-9d5a79f0cedb.png)

**Comment by majkinetor** [comment]
This is really needed for monorepos.
