### ISSUE TITLE
Feature Request: Solution Files (Add / View / Remove)

### ISSUE THREAD

**Issue by LazerFX** [fernandoescolar/vscode-solution-explorer#57]
When developing a solution, quite often you want files to be associated that are not directly included with any project.  Examples of this are Azure Pipelines vsts-ci.yml, docker-compose.yml (And associated sub-files), readme.md and associated readme and wiki sources, etc.

It would be nice if solution explorer allowed us to associate solution files with the solution in the same way Visual Studio does.  This would not affect the file's position on the filesystem, but place a virtual marker in the solution explorer.

For how this would work, see the default Visual Studio solution explorer, where you can do this quite simply.

**Comment by fernandoescolar** [comment]
related with #61

**Comment by fernandoescolar** [comment]
Now you can see solution files, but you can not add or delete them...

**Comment by LazerFX** [comment]
That's great, if using visual studio code as primary editor, I can still use the dot net sln command to handle adding files - or just add them manually.

**Comment by rosostolato** [comment]
On version 0.3.1, the new create file option is causing error:

> error: Can not create file: TypeError: Cannot read property 'push' of undefined

**Comment by fernandoescolar** [comment]
Hi @rosostolato,

Would you mind to give me more details?

- Have you created the vscode-solution-explorer templates for your solution?
- How are you launching the command?
- Which file name have you set in?

Thank you in advance!

**Comment by rsaltrelli** [comment]
I'd also like this feature.  I use VS Code exclusively and have to bounce back to the standard File Explorer to access solution-level files like `docker-compose.yml` and `README.md`.  I would love to be able to access these from within Solution Explorer instead.

**Comment by tho666** [comment]
I'd also like for the extension to include support for adding files as links, similar to Visual Studio's implementation.
I plan on using VsCode exclusively and this is the only thing keeping me from doing so.
Btw: Great extension!
Thanks.
