### ISSUE TITLE
I can't find solution explorer

### ISSUE THREAD

**Issue by mbj2014** [fernandoescolar/vscode-solution-explorer#59]
VSCode
版本: 1.29.1 (system setup)
提交: bc24f98b5f70467bc689abf41cc5550ca637088e
日期: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64

vscode-solution-explorer 0.3.0

After I installed vscode-solution-explorer and restart vscode, I can't find the solution-explorer in EXPLORER Window.

In EXTENSIONS Window, vscode-solution-explorer status is Enable, I can disable or uninstall it.

I try uninstall chinese language pack to fix this issue, but did't effictive.

**Comment by fernandoescolar** [comment]
Hi @ mbj2014,

In the last version I have changed the extension default behavior. Now the "show mode" is set in the activity bar and the track active item is disabled.

So if you want to see the solution explorer in the explorer panel, you have to change some user params:

- Go to "User settings" view. You can execute the command ctrl+shift+p (cmd+shift+p in mac) and search "Perferences: Open User Settings" option.
- In the left tree view, select "Extensions" -> "vscode-solution-explorer configuration"
- In the right panel look for  "Vssolution: Show Mode" and select the option "explorer".

Now if you reload the vscode you can see the solution explorer in panel you expected it.

**Comment by mbj2014** [comment]
Thank you!
but when I change vssolution:Show Mode to explorer, and restart vscode, I could't find the solution explorer.

{
    "vssolution.showMode": "explorer"
}

**Comment by fernandoescolar** [comment]
Could you try to open a Folder and them check in the context menu that appears after clicking with the right  mouse button if the solution explorer is there?
![screenshot 2018-11-20 at 09 17 22](https://user-images.githubusercontent.com/3491424/48760163-787cbd80-eca5-11e8-9f7c-09849513d093.png)

*Note: You have to open a folder in order to view the solution explorer panel.

**Comment by mbj2014** [comment]
Yes. When I open a folder, I can see the Solution Explorer.
