### ISSUE TITLE
Respect the Icons

### ISSUE THREAD

**Issue by mzhukovs** [fernandoescolar/vscode-solution-explorer#62]
Nice extension, thanks.

Most people will have icon packs (e.g. vscode-icons extension) installed in vscode, it would be nice if the solution explorer rendered those same icons as they are in the regular file explorer.

**Comment by fernandoescolar** [comment]
Hi @mzhukovs,

You can make the solution explorer use the current theme icons, setting the parameter "vssolution.solutionExplorerIcons" to "current-theme".

![image](https://user-images.githubusercontent.com/3491424/50132962-e529ae80-0289-11e9-8334-56f8cdbd8e05.png)

Thanks!

**Comment by mzhukovs** [comment]
should have checked there first.... thanks a lot!

**Comment by Coupz** [comment]
I think that should be the default setting. Thanks for letting us know @fernandoescolar.
