### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [fernandoescolar/vscode-solution-explorer#67]
- Issue Type: `Performance`
- Extension Name: `vscode-solution-explorer`
- Extension Version: `0.3.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

[fernandoescolar.vscode-solution-explorer-unresponsive.cpuprofile.txt](https://github.com/fernandoescolar/vscode-solution-explorer/files/2855919/fernandoescolar.vscode-solution-explorer-unresponsive.cpuprofile.txt)

**Comment by fernandoescolar** [comment]
I have configure a compilation using webpack in order to have only a bundle and reduce the load time. I hope it helps with this issue...
