### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 8RockStar8** [fernandoescolar/vscode-solution-explorer#68]
- Issue Type: `Performance`
- Extension Name: `vscode-solution-explorer`
- Extension Version: `0.3.1`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/xtech/fernandoescolar.vscode-solution-explorer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by fernandoescolar** [comment]
#67
