### ISSUE TITLE
PowerShell projects are not recognised

### ISSUE THREAD

**Issue by milesbuckton** [fernandoescolar/vscode-solution-explorer#70]
If you open the Solution, then navigate to the PowerShell Script Project - you are unable to expand all the folders, and see the details. The error states it's an "Unknown project type".

![solution view](https://user-images.githubusercontent.com/37063023/54028414-8cddbb00-41ad-11e9-843e-58f1473ab18e.PNG)

**Comment by fernandoescolar** [comment]
#64 Duplicated
