### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Weiged** [fernandoescolar/vscode-solution-explorer#77]
- Issue Type: `Performance`
- Extension Name: `vscode-solution-explorer`
- Extension Version: `0.3.1`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/dazhu/fernandoescolar.vscode-solution-explorer-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by fernandoescolar** [comment]
#67
