### ISSUE TITLE
Support for subfolder

### ISSUE THREAD

**Issue by julichan** [fernandoescolar/vscode-solution-explorer#78]
Hello,

I have tested your extension which sounds great but I can't use it as is because:
 - It doesn't look for sln files when using for workspaces feature of visual studio code
 - It doesn't look for sln in subfolders of a selected folder either but only in their root.

Thanks a lot.

**Comment by fernandoescolar** [comment]
Hello,

- The first point is duplicated: see # 50
- To load solutions in alternative folders, see the configuration of the user parameter `vssolution.altSolutionFolders`

Thank you very much for your comment.
