### ISSUE TITLE
Can not create file: Error: Cannot find module

### ISSUE THREAD

**Issue by sanjeevaraok** [fernandoescolar/vscode-solution-explorer#79]
I am trying to add cs file to csproj in vscode by using solution explorer. But while adding i am getting
 **error: Can not create file: Error: Cannot find module '\.vscode\solution-explorer\template-parameters.js'**
Can you please help me to resolve.

**Comment by pjangam** [comment]
:+1

**Comment by pedrohex** [comment]
Having this problem too. Begin happening when opened the solution with VS for mac 2019.

**Comment by LadoBago** [comment]
The same problem - error: Can not create file: Error: Cannot find module '.vscodesolution-explorer	emplate-parameters.js'

p.s. version 0.3.3

thanks

**Comment by fernandoescolar** [comment]
There is a problem with webpack and the use of “require” with external js files. @LadoBago could you tell me your OS and VSCode version?

**Comment by fernandoescolar** [comment]
@pedrohex could you tell me if the v0.3.3 has solved this problem in macOS?

Thank you in advance!

**Comment by Gen001** [comment]
Creating files on v0.3.3 now work on my macOS. Thanks.

**Comment by pedrohex** [comment]
> @pedrohex could you tell me if the v0.3.3 has solved this problem in macOS?
> 
> Thank you in advance!

@fernandoescolar , solved! Thank you!
