### ISSUE TITLE
Error when loading folder with .sln file

### ISSUE THREAD

**Issue by AlphaComposite** [fernandoescolar/vscode-solution-explorer#80]
"Cannot read property 'forEach' of undefined"
![image](https://user-images.githubusercontent.com/25360554/57065034-d25fc580-6cd0-11e9-8705-93c9edf21b56.png)

**Comment by fernandoescolar** [comment]
#25 reopened

**Comment by AlphaComposite** [comment]
This issue still exists.

**Comment by fernandoescolar** [comment]
> This issue still exists.

Would you mind to attach the .sln file and the .csproj or other similars with these kind of problems?

**Comment by myall200** [comment]
![error](https://user-images.githubusercontent.com/10205986/59327106-28397b80-8d1b-11e9-9704-3ac708a26318.png)
My project file has null item
like this:
<ItemGroup>
    
  </ItemGroup>

**Comment by myall200** [comment]
<ItemGroup>
    
  </ItemGroup>

**Comment by myall200** [comment]
ItemGroup not include any item.

**Comment by martinothamar** [comment]
Ran into this as well, had an `<ItemGroup />` for some reason in one of the projects. Worked well as soon as I removed it.

Maybe we can:
`element.elements = element.elements || []`
or something?
