### ISSUE TITLE
Only one file is recognized in the project

### ISSUE THREAD

**Issue by Sockman1** [fernandoescolar/vscode-solution-explorer#82]
This is an odd thing, and it could be something I did wrong but for some reason the extension is only recognizing one file and it's header. The file isn't in all these folders either, only in common. I also have another project in the same solution that works just fine.

This is on linux mint, with a project that works fine on windows. As far as I can tell there are no errors.

![image](https://user-images.githubusercontent.com/25406449/57410648-6510d080-71b9-11e9-88bb-e5481a40c664.png)

**Comment by fernandoescolar** [comment]
Would you mind to attach the .sln file and the .csproj or other similars with these kind of problems?
