### ISSUE TITLE
Omnisharp/msbuild configuration

### ISSUE THREAD

**Issue by julichan** [fernandoescolar/vscode-solution-explorer#86]
Hello,

Omnisharp is also able to use msbuild.exe instead of dotnet.exe, please reuse omnisharp commands in vs solution explorer for build, clean and restore commands.

For your reference, omnisharp.json is located in at the root of a workspace to manage build settings. Basically, it can contain this:
{
"msbuild": {
       "enabled": true,
       "ToolsVersion": "15.0",
  },
 "dotnet": {
       "enabled": false,
       "enablePackageRestore": false,
  }
}

**Comment by fernandoescolar** [comment]
You may be able to modify the command settings and create your own: https://github.com/fernandoescolar/vscode-solution-explorer#run-dotnet-commands-in-solutions-and-projects
