### ISSUE TITLE
Support Copy/Move Files with Drag & Drop

### ISSUE THREAD

**Issue by fitdev** [fernandoescolar/vscode-solution-explorer#9]
It would be great if there was drag & drop support for file move and copy operations within project items.

**Comment by fernandoescolar** [comment]
We will have to wait for vscode team to develop this feature: https://github.com/Microsoft/vscode/issues/32592

**Comment by fitdev** [comment]
I see. Thank you for explanation. Hopefully VS Code Team will add it soon.
