### ISSUE TITLE
Go To Defination not wokring in visual studio code.

### ISSUE THREAD

**Issue by jay-doshi** [fernandoescolar/vscode-solution-explorer#91]
#bug

After adding "vscode-solution-explorer" extensions in visual studio code, go to definition not working. 

I have installed VS Code(Version: 1.36.1). My machine also has installed Visual Studio 2013. 

Any other configuration or extension requires for Go To Definition feature.

**Comment by jay-doshi** [comment]
#bug

**Comment by fernandoescolar** [comment]
"Go to definition" is a feature of omnisharp. This extensions does not add such feature :(.
