### ISSUE TITLE
Feature Request: Configurable Line Endings (I can make the pull request)

### ISSUE THREAD

**Issue by jesperbjensen** [fernandoescolar/vscode-solution-explorer#96]
It looks like that the plugin always writes project files using LF line-endings.

We normally have CRLF for our csproj files - so I would like to be able to configure or detect what line endings a file have - and stick to that.

It sadly looks like that xml-js does not have a setting to convert the line endings - so we need to find some recommended way to do that after the fact.

I am ready to give it a try and make a pull request for it - but I wanted to raise the issue on GitHub - so we can discuss the right solution.

**Comment by jesperbjensen** [comment]
I have a working prototype using the [eol](https://www.npmjs.com/package/eol) module. It simple just calls that after creating the XML. If that library is okay to add as a dependency - when it should be easy.

**Comment by fernandoescolar** [comment]
Any PR will be welcome :)
