### ISSUE TITLE
Utilize <RootNamespace> in csproj file

### ISSUE THREAD

**Issue by dzhang-quest** [fernandoescolar/vscode-solution-explorer#97]
When creating C# files using templates, the root namespace is ignored. The name space is generated from the project paths.

It's better to utilize the <RootNamespace> in .csproj file. Not all projects have default namespace same as their directory name.

**Comment by jvrooyen** [comment]
I changed my `template-parameters.js` (the one in my workspace) to

```ts
var path = require("path");
var fs = require("fs");

module.exports = function(filename, projectPath, folderPath) {
    var namespace = "Unknown";
    if (projectPath) {
        namespace = path.basename(projectPath, path.extname(projectPath));
        const projXml = fs.readFileSync(projectPath, 'utf8');
        if (projXml) {
            var rootNamespace = projXml.split(/\r?\n/)
                .find(x => /<RootNamespace>.*<\/RootNamespace>/.test(x));
            if (rootNamespace) {
                namespace = /<RootNamespace>(.*)<\/RootNamespace>/.exec(rootNamespace)[1];
            }
        }

... remainder of the file unchanged
```

This change tries to "parse" the XML project file looking for the `RootNamespace` element. I do not know where to get hold of an XML parser/*proj file DOM in the context of this script, so the parse logic is fragile and depends on the current *proj file formatting.

If this can be remedied, I can code a PR for this.
