### ISSUE TITLE
Focus is broken when vssolution.trackActiveItem is true

### ISSUE THREAD

**Issue by imurashkawgames** [fernandoescolar/vscode-solution-explorer#98]
Now when you going to some file (trl+t) and option vssolution.trackActiveItem is true, focus will be in solution explorer but not in code editor.

**Comment by fernandoescolar** [comment]
People from vscode added this feature in the extensions API but it never has worked well... I'm sorry. I have not removed this option because I thing maybe in a new version it will work.
